#!/bin/bash

if [ ! -f "$1" ]; then
  echo usage: "$0" '{specfile}'
  exit 1
fi

set -e
deps="$(rpmspec --srpm -q "$1" --qf '[%{REQUIRENAME} ]')"
manualinstalled="$(apt-mark showmanual $deps)"
if [ $(echo "$deps" | wc -w) -ge 1 ]; then
  sudo sh -ec "
    apt-get install $deps
    apt-mark auto $deps
    if [ $(echo "$manualinstalled" | wc -w) -ge 1 ]; then
      apt-mark manual $manualinstalled
    fi
  "
fi
rpmbuild -ba "$1" --nodeps
fakeroot alien -k --scripts ~/rpmbuild/RPMS/$(rpmspec --srpm -q "$1" --qf '%{ARCH}')/$(rpmspec --srpm -q "$1" --qf '%{NAME}-%{VERSION}-%{RELEASE}.%{ARCH}.rpm')
