#!/bin/bash

set -e

spec=
clean=false

while [ -n "$1" ]; do
  case "$1" in
  -c)
    clean=true
    ;;
  *)
    spec="$(realpath "$1")"
    ;;
  esac
  shift
done

if [ ! -f "$spec" ]; then
  echo usage: "$0 [-c] {specfile}"
  exit 1
fi

deps="$(echo $(rpmspec --srpm -q "$spec" --qf '[%{REQUIRENAME} ]'))"
manualinstalled="$(echo $(apt-mark showmanual $deps))"
pkgname="$(rpmspec --srpm -q "$spec" --qf "%{NAME}")"
pkgver="$(rpmspec --srpm -q "$spec" --qf "%{VERSION}")"
pkgrel="$(rpmspec --srpm -q "$spec" --qf "%{RELEASE}")"
pkgarch="$(rpmspec --srpm -q "$spec" --qf "%{ARCH}")"
if [ $(echo "$deps" | wc -w) -ge 1 ]; then
  sudo sh -ec "
    apt-get install -y $deps
    apt-mark auto $deps
    if [ $(echo "$manualinstalled" | wc -w) -ge 1 ]; then
      apt-mark manual $manualinstalled
    fi
  "
fi
rpmbuild -bb "$spec" --nodeps
mkdir -p deb
(
  cd deb;
  echo "converting into $pkgname_$pkgver-$pkgrel_$pkgarch.deb..."
  fakeroot alien -k --scripts ~/rpmbuild/RPMS/$pkgarch/$pkgname-$pkgver-$pkgrel.$pkgarch.rpm
)
if $clean; then
  rpmbuild --nodeps --clean "$spec"
fi
