#!/bin/sh

cd "$(dirname "$0")"
for pkg in $(cat series | sed -n 's#wandbox-boost-\(.*\)-gcc-\(.*\)#\1,\2#gp'); do
  boostver=$(echo $pkg | cut -d, -f1)
  gccver=$(echo $pkg | cut -d, -f2)
  boostver_tarname=$(echo $boostver | sed 's/\./_/g')
  sed -e "s#@@boostver@@#$boostver#g" -e "s#@@gccver@@#$gccver#g" -e "s#@@boostver_tarname@@#$boostver_tarname#g" > specs/wandbox-boost-$boostver-gcc-$gccver.spec <<EOF
Summary: boost for wandbox
Name: wandbox-boost-@@boostver@@-gcc-@@gccver@@
Version: @@boostver@@
Release: 1
License: Boost
Group: wandbox
BuildRoot: %{_tmppath}/%{name}-%{version}-%{release}-buildroot
BuildRequires: wandbox-gcc-head libbz2-dev python-dev
Source0: http://downloads.sourceforge.net/project/boost/boost/@@boostver@@/boost_@@boostver_tarname@@.tar.gz
Source1: boost-1.48.0-gcc-head-fix-stdlibcpp3-config.patch
Source2: boost-1.47.0-gcc-head-fix-stdlibcpp3-config.patch
URL: http://melpon.org/wandbox

%define _prefix /opt/wandbox/boost-@@boostver@@-gcc-@@gccver@@
%define _gccdir /opt/wandbox/gcc-@@gccver@@

%description
a component of wandbox service

%prep
%setup -q -n boost_@@boostver_tarname@@

%build
cp %{SOURCE1} %{SOURCE2} .
find . -maxdepth 1 -name 'boost-@@boostver@@-gcc-@@gccver@@*.patch' -print0 | xargs -0 cat | patch -p1
LD_LIBRARY_PATH=%{_gccdir}/lib:%{_gccdir}/lib64 PATH=%{_gccdir}/bin:$PATH ./bootstrap.sh --prefix=%{_prefix}
sed "s#using[ 	]*gcc.*;#using gcc : : %{_gccdir}/bin/g++ ;#" -i project-config.jam
LD_LIBRARY_PATH=%{_gccdir}/lib:%{_gccdir}/lib64 ./b2 stage release link=shared runtime-link=shared --without-mpi %{_smp_mflags}

%install
LD_LIBRARY_PATH=%{_prefix}/lib:%{_prefix}/lib64 ./b2 install release link=shared runtime-link=shared --without-mpi --prefix=%{buildroot}%{_prefix}
rm -rf %{buildroot}%{_prefix}/share
rm -rf %{buildroot}%{_prefix}/docs

%clean
rm -rf %{buildroot}

%files
%defattr(-,root,root,-)
%{_prefix}/include
%{_prefix}/lib

%changelog
 * Sun Jun 26 2014 kikairoya <kikairoya@gmail.com>
 - Initial build

EOF
done
