Default: &defaults
  host: "127.0.0.1"
  port: 3000
  copyright: (C) 2013-2014 @melponn
  auth: false
  vm_host: "127.0.0.1"
  vm_port: 2012

Development:
  <<: *defaults

Testing:
  <<: *defaults

Staging:
  <<: *defaults

Production:
  <<: *defaults
#  approot: "http://example.com/services/wandbox"
