#!/bin/bash

cd "$(dirname "$0")"
for ver in $(cat ../series/* | sed -n 's#wandbox-php-\([0-9]\+\.[0-9]\+\.[0-9]\+\)#\1#gp'); do
  cat > ../specs/wandbox-php-$ver.spec <<EOF
Summary: php for wandbox
Name: wandbox-php-$ver
Version: $ver
Release: 4
License: PHP
Group: wandbox
BuildRoot: %{_tmppath}/%{name}-%{version}-%{release}-buildroot
BuildRequires: libxml2-dev
Source0: http://jp1.php.net/distributions/php-$ver.tar.gz
URL: http://melpon.org/wandbox

%define _prefix /opt/wandbox/php-%{version}
%define _sysconfdir %{_prefix}/etc

%description
a component of wandbox service

%prep
%setup -q -n php-%{version}

%build
%{configure} --disable-cgi
%{__make} %{_smp_mflags}

%install
%{make_install} INSTALL_ROOT=%{buildroot}
rm -rf %{buildroot}%{_prefix}/share
rm -rf %{buildroot}/.??* %{buildroot}/etc/pear.conf

%clean
rm -rf %{buildroot}

%files
%defattr(755,root,root,755)
%{_bindir}
%defattr(644,root,root,755)
%{_includedir}
%{_libdir}
%{_sysconfdir}

%changelog
* Sat Jun 6 2015 kikairoya <kikairoya@gmail.com>
- use generator

* Mon Jun 16 2014 kikairoya <kikairoya@gmail.com>
- dependencies

* Sun Jun 15 2014 kikairoya <kikairoya@gmail.com>
- glob forgotten file

* Sat Jun 14 2014 kikairoya <kikairoya@gmail.com>
- Initial build
EOF
done
